// bigCities.js
const bigCities = [
  "new york",
  "los angeles",
  "chicago",
  "houston",
  "phoenix",
  "philadelphia",
  "san antonio",
  "san diego",
  "dallas",
  "san jose",
  "austin",
  "jacksonville",
  "fort worth",
  "columbus",
  "charlotte",
  "indianapolis",
  "san francisco",
  "seattle",
  "denver",
  "washington",
  "nashville",
  "oklahoma city",
  "el paso",
  "boston",
  "portland",
  "las vegas",
  "detroit",
  "memphis",
  "louisville",
  "baltimore",
  "milwaukee",
  "albuquerque",
  "tucson",
  "fresno",
  "mesa",
  "sacramento",
  "atlanta",
  "kansas city",
  "colorado springs",
  "miami",
  "raleigh",
  "omaha",
  "long beach",
  "virginia beach",
  "oakland",
  "minneapolis",
  "tulsa",
  "arlington",
  "new orleans",
  "wichita",
  "cleveland",
  "tampa",
  "bakersfield",
  "aurora",
  "honolulu",
  "anaheim",
  "santa ana",
  "corpus christi",
  "riverside",
  "lexington",
  "stockton",
  "henderson",
  "saint paul",
  "st. louis",
  "cincinnati",
  "pittsburgh",
  "greensboro",
  "anchorage",
  "plano",
  "lincoln",
  "orlando",
  "irvine",
  "newark",
  "durham",
  "chula vista",
  "toledo",
  "fort wayne",
  "st. petersburg",
  "laredo",
  "jersey city",
  "chandler",
  "madison",
  "lubbock",
  "scottsdale",
  "reno",
  "buffalo",
  "gilbert",
  "glendale",
  "north las vegas",
  "winston–salem",
  "chesapeake",
  "norfolk",
  "fremont",
  "garland",
  "irving",
  "hialeah",
  "richmond",
  "boise",
  "spokane",
  "baton rouge",
  "des moines",
  "tacoma",
  "san bernardino"
];

export default bigCities;
